# ================================== Iuputs ===================================
filebeat.inputs:
- type: log

  enabled: true
  paths: 
    - e:\Kingdee\eas\admin\logs\datacenterupgrade.log
  multiline.type: pattern
  multiline.pattern: ^\[
  multiline.negate: true
  multiline.match: after
# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
# ================================== Outputs ===================================
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["localhost:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

